[tool.poetry]
name = "hw5"
version = "0.1.0"
description = ""
authors = ["alexbuyan <sashabuyan@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
